---
- name: Add new target to ASP.NET.yml
  hosts: localhost
  become: yes
  gather_facts: no
  vars_prompt:
    - name: new_target
      prompt: "Enter the new target address (e.g., 172.16.28.3:44325)"
      private: no

  tasks:
    - name: Read the current file content
      slurp:
        src: ../monitoringfiles/prometheus/targets/ASP.NET.yml
      register: file_content

    - name: Decode the content from base64
      set_fact:
        file_content_decoded: "{{ file_content.content | b64decode }}"

    - name: Check if the new target is already in the file
      set_fact:
        target_exists: "{{ new_target in file_content_decoded }}"

    - name: Validate new target IP address format
      set_fact:
        valid_ip: "{{ new_target | regex_search('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}(?::\\d{1,5})?$') }}"
      when: not target_exists

    - name: Fail if new target is not a valid IP address
      fail:
        msg: "The new target address '{{ new_target }}' is not a valid IP address."
      when: valid_ip is not defined

    - name: Ensure 'targets' section exists
      lineinfile:
        path: ../monitoringfiles/prometheus/targets/ASP.NET.yml
        line: '- targets:'
        create: yes
        state: present
        insertafter: '^$'

    - name: Insert the new target below existing targets
      block:
        - name: Add the new target
          lineinfile:
            path: ../monitoringfiles/prometheus/targets/ASP.NET.yml
            line: "  - \"{{ new_target }}\""
            create: yes
            state: present
            insertafter: '^- targets:'
          when: not target_exists
      when: not target_exists

#   - name: Copy updated file to remote server
#      copy:
#        src: ../monitoringfiles/prometheus/targets/ASP.NET.yml
#        dest: /opt/monitoring-stack/grafana/prometheus/targets/ASP.NET.yml
#        mode: '0644'
