- name: Copy grafana,prometheus compose and yml
  hosts: monitoring
  become: yes
  become_user: root
  tasks:
    - name: Ensure the directory exists
      file:
        path: /opt/monitoring-stack/grafana
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml with dynamic hostname
      template:
        src: ./monitoringfiles/grafana/docker-compose.yml
        dest: /opt/monitoring-stack/grafana/docker-compose.yml

    - name: Ensure the directory exists for prometheus
      file:
        path: /opt/monitoring-stack/prometheus
        state: directory
        mode: '0755'

    - name: Copy prometheus.yml
      copy:
        src: ./monitoringfiles/prometheus/prometheus.yml
        dest: /opt/monitoring-stack/prometheus/prometheus.yml

    - name: Ensure the directory exists for prometheus targets
      file:
        path: /opt/monitoring-stack/prometheus/targets
        state: directory
        mode: '0755'


    - name: Copy all targets
      copy:
        src: ./monitoringfiles/prometheus/targets/
        dest: /opt/monitoring-stack/prometheus/targets/

    - name: Ensure the directory exists for loki
      file:
        path: /opt/monitoring-stack/loki
        state: directory
        mode: '0755'

    - name: Copy loki.yml
      copy:
        src: ./monitoringfiles/loki/loki-local-config.yml
        dest: /opt/monitoring-stack/loki/loki-local-config.yml

    - name: Ensure the directory exists for promtail
      file:
        path: /opt/monitoring-stack/promtail
        state: directory
        mode: '0755'
    - name: Copy promtail.yml
      copy:
        src: ./monitoringfiles/promtail/promtail-local-config.yml
        dest: /opt/monitoring-stack/promtail/promtail-local-config.yml

    - name: Ensure the directory exists for prom_data
      file:
        path: /opt/monitoring-stack/prometheus/prom_data
        state: directory
        mode: '0777'

    # - name: Ensure the directory exists for grafana_data
    #   file:
    #     path: /opt/monitoring-stack/grafana/grafana_data
    #     state: directory
    #     mode: '0777'
      
    - name: Create Docker volume for grafana and prometheus
      command: docker volume create grafana_data
      ignore_errors: yes
    # - name: Change permissions of the directory
    #   file:
    #     path: /opt/monitoring-stack/prometheus/prom_data
    #     mode: '0755'
    #     owner: youruser
    #     group: yourgroup

    - name: Run docker-compose up -d
      command: docker compose up -d
      args:
        chdir: /opt/monitoring-stack/grafana/

