- name: Copy grafana,prometheus compose and yml
  hosts: monitoring
  become: yes
  become_user: root
  tasks:
    - name: Ensure the directory exists
      file:
        path: /opt/monitoring-stack/grafana
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml with dynamic hostname
      template:
        src: ./monitoringfiles/grafana/docker-compose.yml
        dest: /opt/monitoring-stack/grafana/docker-compose.yml

    - name: Ensure the directory exists for prometheus
      file:
        path: /opt/monitoring-stack/grafana/prometheus
        state: directory
        mode: '0755'

    - name: Copy prometheus.yml
      copy:
        src: ./monitoringfiles/prometheus/prometheus.yml
        dest: /opt/monitoring-stack/grafana/prometheus/prometheus.yml

    - name: Run docker-compose up -d
      command: docker-compose -f /opt/monitoring-stack/grafana/docker-compose.yml up -d
      # args:
      #   chdir: /home/youruser

