name: Install Docker and Docker Compose
  hosts: all
  become: yes
  vars:
    docker_compose_version: latest

  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Check if Docker is installed
      command: "docker --version"
      ignore_errors: true
      register: docker_installed

    - name: Check if Docker Compose is installed
      command: "docker-compose --version"
      ignore_errors: true
      register: docker_compose_installed

    - name: Install Docker if not already installed
      shell: >
        curl -fsSL https://get.docker.com -o get-docker.sh && \
        sudo sh get-docker.sh
      when: docker_installed.rc != 0

    - name: Get latest Docker Compose version from GitHub
      when: docker_compose_version == 'latest'
      become: no
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: docker_compose_latest

    - name: Extract latest version number
      when: docker_compose_version == 'latest'
      set_fact:
        docker_compose_version: "{{ docker_compose_latest.json.tag_name }}"

    - name: Install Docker Compose
      become: yes
      shell: >
        sudo curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
        sudo chmod +x /usr/local/bin/docker-compose
      when: docker_compose_installed.rc != 0

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
      when: docker_installed.rc == 0