- name: Copy Docker Compose and Netdata Config Files
  hosts: monitoring
  become: yes
  vars_prompt:
    - name: host_name
      prompt: "Enter the host name"
      private: no
  tasks:
    - name: Ensure the directory exists
      file:
        path: /opt/monitoring-stack/netdata
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml with dynamic hostname
      template:
        src: ./monitoringfiles/netdata/docker-compose.yml.j2
        dest: /opt/monitoring-stack/netdata/docker-compose.yml
      vars:
        hostname: "{{ host_name }}"

    - name: Copy netdata.conf
      copy:
        src: ./monitoringfiles/netdata/netdata.conf
        dest: /opt/monitoring-stack/netdata/netdata.conf

