global:
  scrape_interval: 3m

scrape_configs:
  - job_name: "RDS_WMI"
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/RDS_WMI.yml

  - job_name: "prometheus"
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/prometheus.yml

  - job_name: "CLOUD NETDATA"
    metrics_path: /api/v1/allmetrics
    params:
      format: [prometheus_all_hosts]
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/CLOUD_NETDATA.yml

  - job_name: "hana & SL server"
    metrics_path: /api/v1/allmetrics
    params:
      format: [prometheus_all_hosts]
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/hana_SL_server.yml

  - job_name: "node-exporters"
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/node-exporters.yml

  - job_name: "data-analytics_PG"
    metrics_path: /api/v1/allmetrics
    params:
      format: [prometheus_all_hosts]
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/data-analytics_PG.yml

  - job_name: "ETL-PENTAHO"
    metrics_path: /api/v1/allmetrics
    params:
      format: [prometheus_all_hosts]
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/ETL-PENTAHO.yml

  - job_name: "ASP.NET"
    file_sd_configs:
      - files:
        - /opt/monitoring-stack/grafana/prometheus/targets/ASP.NET.yml
